config:
  vault:
    url: http://vault-internal.vault-1.svc.cluster.local:8200
    insecure: true
    timeout: 5m
    auth:
      approle:
        role: "25d837e2-81f5-479f-1c00-509fb76c17e5"
        secret: "e14f5aaf-2324-2e1b-0b93-f5ec1dcfb3b8"
  snapshots:
    frequency: 1h
    retain: 10
    namePrefix: "agent-"
    storages:
      local:
        enabled: true
        retain: 10
        path: /vault/snapshots
        volume:
          persistentVolumeClaim:
            create: true
            storageClassName: "openebs-hostpath"
            accessMode: "ReadWriteOnce"

