expose:
  type: nodePort
  tls:
    enabled: true 
    auto: 
      commonName: "harbor"
persistence:
  persistentVolumeClaim:
    registry:
      subPath: "harbor"
      accessMode: ReadWriteOnce
      size: 10Gi
  
trivy:
  enabled: false
metrics:
  enabled: true
  serviceMonitor:
    enabled: true