injector:
  metrics:
    enabled: true
server:
  annotations:
    reloader.stakater.com/auto: "true"
  auditStorage:
    enabled: true
    storageClass: openebs-hostpath
  dataStorage:
    size: 30Gi
    storageClass: openebs-hostpath
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 256Mi
ui:
  enabled: true
  serviceType: LoadBalancer
