injector:
  metrics:
    enabled: true
server: 
  dataStorage:
    storageClass: openebs-hostpath
    size: 30Gi
  auditStorage:
    enabled: true
    storageClass: openebs-hostpath
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 256Mi
      cpu: 250m
ui: 
  enabled: true
  serviceType: "LoadBalancer"
