

server:
  nodeSelector:
    kubernetes.io/hostname: master
  auditStorage:
    enable: true
    storageClass: "openebs-hostpath"
  standalone:
    enabled: true
    config: |
      disable_mlock = true
      ui=true

      storage "raft" {
        path = "/vault/data",
        node_id = "vault-0"
      }

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        # Enable unauthenticated metrics access (necessary for Prometheus Operator)
        #telemetry {
        #  unauthenticated_metrics_access = "true"
        #}
      }
      seal "transit" {
        address = "http://vault-internal.vault-transit.svc.cluster.local:8200"
        token = "hvs.CAESIIfEnemQdNWlXxm6na_gFMMADWKDReIAGdVhUfH9HHAPGh4KHGh2cy40NFpJSVkwOW9Id3ZJOFFITUhsa2tOa2w"
        disable_renewal = "false"
        key_name = "vault-1"
        mount_path = "transit/vault-1/"
        tls_skip_verify = "true"
      }
     



