annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Update common Helm release to v1.5.1
    - kind: added
      description: Add OCI install docs
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/bastienwirtz/homer
    - name: Chart Source
      url: https://github.com/gabe565/charts/tree/main/charts/homer
apiVersion: v2
appVersion: v23.05.1
dependencies:
- name: common
  repository: https://bjw-s.github.io/helm-charts
  version: 1.5.1
description: A dead simple static HOMepage for your servER to keep your services on
  hand, from a simple yaml configuration file.
home: https://charts.gabe565.com/charts/homer/
icon: https://raw.githubusercontent.com/bastienwirtz/homer/5609315fe77da5441a9c3dda8d92c0ffe9f1bf17/public/assets/icons/logo.svg
keywords:
- homer
- dashboard
- startpage
- homepage
kubeVersion: '>=1.22.0-0'
name: homer
sources:
- https://github.com/bastienwirtz/homer
type: application
version: 0.7.1
