resources:
  limits:
    cpu: "1"
    memory: "2Gi"
  requests:
    cpu: "500m"
    memory: "1Gi"
replicaCount: 1           
auth:
  adminPassword: ref+vault://kubernetes/adminpassword?proto=http#/password
global:
  storageClass: "openebs-hostpath"
postgresql:
  auth:
    postgresPassword: ref+vault://kubernetes/adminpassword?proto=http#/password
    password: ref+vault://kubernetes/adminpassword?proto=http#/password
service:
  type: NodePort