resources:
  limits:
    cpu: "1"
    memory: "2Gi"
  requests:
    cpu: "500m"
    memory: "1Gi"
service:
  type: LoadBalancer
replicaCount: 2
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPU: "80"
  targetMemory: "80"

global:
  storageClass: "openebs-hostpath"
