controller:
  kind: DaemonSet
  resources:
    limits:
      cpu: 500m
      memory: 300Mi
    requests:
      cpu: 200m
      memory: 200Mi
  admissionWebhooks:
    enabled: false
  replicaCount: 3
  config:
    use-forwarded-headers: "true"