# Default values for semaphore.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

semaphore: 
  env:
    SEMAPHORE_DB_USER: ref+vault://kubernetes/semaphore?proto=http#/username
    SEMAPHORE_DB_PASS: ref+vault://kubernetes/semaphore?proto=http#/password
    SEMAPHORE_DB: ref+vault://kubernetes/semaphore?proto=http#/database
    SEMAPHORE_ACCESS_KEY_ENCRYPTION: ref+vault://kubernetes/semaphore?proto=http#/accesskey
  persistence:
    storageClass: "openebs-hostpath"
  service:
    type: ClusterIP
    port: "3000"
  image:
    tag: "v2.9.19"