certmanager:
  install: false
  installCRDs: false
  rbac:
    create: false
gitlab:
  toolbox:
    enabled: false
gitlab-runner:
  install: false
global:
  ingress:
    configureCertmanager: false
    enabled: false
  kas:
    enabled: false
  minio:
    enabled: false
  serviceAccount:
    enabled: true
nginx-ingress:
  enabled: false
postgresql:
  auth:
    password: 5R7V4btp(6Jg?}j9>v"2
    postgresPassword: 1m4-VnioanxkTB79hV11
prometheus:
  install: false
  rbac:
    create: false
redis:
  auth:
    existingSecretKey: '@~"76~5l;z4ydv$C,7UA'
upgradeCheck:
  enabled: false
