mode: distributed
commonAnnotations:
  reloader.stakater.com/auto: "true"
auth:
  rootUser: ref+vault://kubernetes/minio?proto=http#/root_user
  rootPassword: ref+vault://kubernetes/minio?proto=http#/root_password
deployment:
  updateStrategy:
   type: RollingUpdate

podLabels: 
  usage: s3bucket

persistence:
  enabled: true
  storageClass: "openebs-hostpath"
  size: 5Gi
service:
  type: NodePort
statefulset:
  replicaCount: 2
  drivesPerNode: 2