mode: distributed
commonAnnotations:
  reloader.stakater.com/auto: "true"
auth:
  rootUser: ref+vault://kubernetes/minio?proto=http#/root_user
  rootPassword: ref+vault://kubernetes/minio?proto=http#/root_password
deployment:
  updateStrategy:
   type: RollingUpdate

podLabels: 
  usage: s3bucket
resources:
  limits:
     cpu: 500m
     memory: 2Gi
  requests:
     cpu: 500m
     memory: 2Gi
persistence:
  enabled: true
  storageClass: "openebs-hostpath"
  size: 10Gi
service:
  type: NodePort
