alertmanager:
  enabled: false
defaultRules:
  rules:
    alertmanager: false
global:
  autoscaling:
    enabled: true
  persistence:
    accessModes:
      - ReadWriteOnce
    enabled: true
    size: 40Gi
    storageClass: openebs-hostpath
    type: pvc
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
grafana:
  adminPassword: Rzb7SU3dV1PPNaV3uu9Z
  livenessProbe:
    failureThreshold: 10
    httpGet:
      path: /api/health
      port: 3000
    initialDelaySeconds: 600
    timeoutSeconds: 30
  nodeSelector:
    kubernetes.io/hostname: master
  persistence:
    enabled: true
    storageClassName: openebs-hostpath
  podAnnotations:
    reloader.stakater.com/auto: "true"
  readinessProbe:
    httpGet:
      path: /api/health
      port: 3000
    initialDelaySeconds: 600
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - authorization:
          credentials: hvs.CAESIB9boDtxyYT3AMBWeCeN7EjnAlZsma827nbD0l9PlNTqGh4KHGh2cy44bzNjckMwTTV1cUl6bHF5SWFVTngxeHo
        job_name: vault
        metrics_path: /v1/sys/metrics
        params:
          format:
            - prometheus
        scheme: http
        static_configs:
          - targets:
              - vault-internal.vault-1.svc.cluster.local:8200
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
