


defaultRules:
  rules:
    alertmanager: false
alertmanager: 
  enabled: false
grafana: 
  adminPassword: ref+vault://kube-stack/kv/grafana?proto=http#/password
  podAnnotations:
    reloader.stakater.com/auto: "true"
  readinessProbe:
    httpGet:
      path: /api/health
      port: 3000
    initialDelaySeconds: 600

  livenessProbe:
    httpGet:
      path: /api/health
      port: 3000
    initialDelaySeconds: 600
    timeoutSeconds: 30
    failureThreshold: 10
  nodeSelector:
    kubernetes.io/hostname: master
  persistence:
    enabled: true
    storageClassName: "openebs-hostpath"
  # deployment:
  #   volumes:
  #     - name: minio-dashboard-config-volume
  #       configMap:
  #         name: minio-dashboard-configmap
  #   volumeMounts:
  #     - name: minio-dashboard-config-volume
  #       mountPath: /etc/grafana/dashboards
  #       readOnly: true
  resources: 
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  # dashboards:
  #   minio-dashboard:
  #     configMapName: minio-dashboard-configmap
  #     items:
  #       - key: minio
  #         path: minio-dashboard.json

    
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    # additionalScrapeConfigs: 
    #   - job_name: minio-job
    #     bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwiZXhwIjo0ODQ1NDU3NDQ5fQ.5cV_jta8roh09afwQ4wmojeFKbx6MowY54w1KAKAZpKBycH9AZlVp73pRPdR3tHx7KWJvZnnx-XEaL6GbSP32Q
    #     metrics_path: /minio/v2/metrics/cluster
    #     scheme: http
    #     static_configs:
    #       - targets: ['minio.minio.svc.cluster.local:9000']
    additionalScrapeConfigs: 
    - job_name: vault
      authorization:
        credentials: "hvs.CAESIB9boDtxyYT3AMBWeCeN7EjnAlZsma827nbD0l9PlNTqGh4KHGh2cy44bzNjckMwTTV1cUl6bHF5SWFVTngxeHo"
      metrics_path: /v1/sys/metrics
      scheme: http
      params:
        format: ['prometheus']
      static_configs:
        - targets: ['vault-internal.vault-1.svc.cluster.local:8200']
    - job_name: postgres-exporter
      metrics_path: "/metrics"
      scrape_interval: 3m
      scrape_timeout: 1m
      static_configs:
        - targets: ['prometheus-postgres-exporter.prometheus-postgres-exporter.svc.cluster.local:9187']
  # service:
  #   type: "LoadBalancer"
  #   loadBalancerIP: "192.168.1.222"

global: 
  persistence:
    type: pvc
    enabled: true
    storageClass: "openebs-hostpath"
    accessModes:
      - ReadWriteOnce
    size: 40Gi
  autoscaling:
    enabled: true
  resources: 
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
